// Ops reference generator (issue 0012 exp 3): one markdown page per op
// category, generated from the local native shell's `torch ops` metadata.
// Never resolves an installed legacy `torch` executable through PATH.
//
//   bun run scripts/gen-ops-reference.ts          # write pages
//   bun run scripts/gen-ops-reference.ts --check  # regenerate + byte-compare
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const OUT = new URL("../content/docs/reference/", import.meta.url).pathname;
const CATEGORY_ORDER = [
  "creation",
  "pointwise",
  "comparison",
  "reduction",
  "linalg",
  "shape",
  "loss",
  "autograd",
  "utility",
];
const TITLES: Record<string, string> = {
  creation: "Creation ops",
  pointwise: "Pointwise ops",
  comparison: "Comparison ops",
  reduction: "Reduction ops",
  linalg: "Linear algebra ops",
  shape: "Shape ops",
  loss: "Loss ops",
  autograd: "Autograd ops",
  utility: "Utility ops",
};

interface Op {
  name: string;
  category: string;
  summary: string;
  usage: string;
}

const shell = new URL("../../../rs/target/release/nutorch", import.meta.url)
  .pathname;
const ops = JSON.parse(
  execFileSync(shell, [
    "--no-config-file",
    "--no-history",
    "-c",
    "use torch; torch ops | to json --raw",
  ]).toString(),
) as Op[];

const byCategory = new Map<string, Op[]>();
for (const op of ops) {
  if (!byCategory.has(op.category)) byCategory.set(op.category, []);
  byCategory.get(op.category)?.push(op);
}

const unknown = [...byCategory.keys()].filter(
  (c) => !CATEGORY_ORDER.includes(c),
);
if (unknown.length) {
  console.error(`unknown categories: ${unknown.join(", ")} — extend the list`);
  process.exit(1);
}

function page(category: string, index: number, entries: Op[]): string {
  const lines: string[] = [
    "---",
    `title: ${String(TITLES[category])}`,
    `description: The ${String(entries.length)} ${category} operation${
      entries.length === 1 ? "" : "s"
    }, generated from the op table.`,
    `order: ${String(20 + index)}`,
    'section: "Reference"',
    "---",
    "",
    "Unreleased native NuTorch shell reference. Generated by",
    "`scripts/gen-ops-reference.ts`; every op also documents itself with",
    "`torch <op> --help`. Tensor operands are native values, not strings.",
  ];
  for (const op of entries) {
    // Display layer: the summary is rendered prose, where the project
    // name is the proper noun NuTorch (issue 0013 exp 6).
    const summary = op.summary.replace(/\bnutorch\b/g, "NuTorch");
    const usage = op.usage.replace(/^usage: /, "");
    lines.push("", `### ${op.name}`, "", summary, "");
    lines.push(
      "Signature (placeholders describe arguments; this is not a runnable example):",
      "",
      "```nu",
      "use torch",
      usage,
      "```",
    );
  }
  lines.push("");
  return lines.join("\n");
}

const generated = new Map<string, string>();
CATEGORY_ORDER.forEach((category, i) => {
  const entries = byCategory.get(category);
  if (!entries) return;
  generated.set(`${category}.md`, page(category, i, entries));
});

if (process.argv.includes("--check")) {
  let stale = false;
  // Orphans: committed files no category produces anymore.
  const { readdirSync } = await import("node:fs");
  for (const file of readdirSync(OUT).filter((f) => f.endsWith(".md"))) {
    if (!generated.has(file)) {
      console.error(`ORPHAN: src/content/docs/reference/${file}`);
      stale = true;
    }
  }
  for (const [file, content] of generated) {
    let committed = "";
    try {
      committed = readFileSync(`${OUT}/${file}`, "utf8");
    } catch {
      /* Storage or optional fixture read may be unavailable. */
    }
    if (committed !== content) {
      console.error(`STALE: src/content/docs/reference/${file}`);
      stale = true;
    }
  }
  if (stale) process.exit(1);
  console.log(
    `ops reference current (${String(ops.length)} ops, ${String(generated.size)} pages)`,
  );
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [file, content] of generated) {
    writeFileSync(`${OUT}/${file}`, content);
  }
  console.log(
    `wrote ${String(generated.size)} pages (${String(ops.length)} ops) → src/content/docs/reference/`,
  );
}
